# Generated by Django 2.0 on 2017-12-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '選択肢', 'verbose_name_plural': '選択肢'},
        ),
    ]
